### ISSUE TITLE
发现一例数据错误（129292）

### ISSUE THREAD

**Issue by tinuv** [cbdb-project/cbdb_sqlite#1]
纪太后的性别应为女性(最新版数据库)
![图片](https://renwuzhi.wiki/images/10.png)

**Comment by sudoghut** [comment]
感谢报错！129292 性别的问题已在录入系统中修正：https://input.cbdb.fas.harvard.edu/basicinformation/129292/edit. 修正后的数据会在下一次公开发布的版本中更新到包括 sqlite 在内的所有数据库格式中。
