### ISSUE TITLE
Lack of Directions to import 7z file into SQLlite

### ISSUE THREAD

**Issue by policybot2020** [cbdb-project/cbdb_sqlite#3]
Hi Maintainers, 

thanks so much for maintaining this package. 

I want to explore the data for my paper I am writing, but there is very little instructions on how to import this database into a python environment or SQLlite. 

Can you provide more directions?

thanks

**Comment by sudoghut** [comment]
Hi @policybot2020,

Thanks for using our data!

- Here you will find the latest version of the SQLite database: https://github.com/cbdb-project/cbdb_sqlite/blob/master/latest.7z. After decompressing the file, you can use Python to read the db file directly.

- Here you will find the explanations of the structure of each table in chapter 2: https://projects.iq.harvard.edu/sites/projects.iq.harvard.edu/files/cbdb/files/cbdb_users_guide.pdf

- Detailed description of tables and fields can be found here: https://docs.google.com/spreadsheets/d/1KNX4FPVbFII0HP2FEiQooGpdONobGM9QVdEIQvGz2h8/edit?pli=1#gid=1668212716

- Here you will find a use case of the query CBDB SQLite database:
https://github.com/cbdb-project/CBDB-disambiguation-automation/blob/883c39589c4020b63b1bb39943a94cb305fc22fd/CBDB-disambiguation-automation.py#L60

- If you are interested in our project, you will find more information here:
https://projects.iq.harvard.edu/cbdb
https://handbook.pubpub.org/pub/case-cbdb/

Best,
Hongsu

**Comment by policybot2020** [comment]
@sudoghut

Thanks very much for your help! I am able to access the database now! I see you are one of the main administrators of this CBDB project. I must say, this is an amazing project! Thanks for your team's hardwork so that researchers like me can do further research. 

My first question, do you already have a list of SQL codes for basic biographical discovery analysis, like joining PERSONS, with PLACES, TIME, EVENTS, split by time periods?

Just a quick introduction my name is [Jianyin Roachell](https://www.shh.mpg.de/person/124281/2375), Chinese American, currently an associate reseacher at Max Planck Institute for Geoanthropology. I am interested in researching complex systemes such as the evolutionary relationship between humans, industry and environment. I would like to see whether I can link up more databases to like the **China Historical Geographic Information System**. 

My question for you, do you know any other free China historical databases about , fore example, China's historical land use, and urbanization, and trade? 

thanks so much Hongsu!

best,

Jian

**Comment by sudoghut** [comment]
You are very welcome! I'm so glad that you are interested in our data! Our former project manager Shih-Pei Chen is also working in Max Planck. She is leading a historical local gazetteers project. You might have known that. My name is Hongsu Wang. You can also find me here: hongsuwang(at)fas.harvard.edu

## Historial sociology data

You might be interested in the 中華大典 series. The 經濟典 includes lots of information about population, land use, urbanization, and trade:

[中華大典 經濟典 土地制度分典](https://archive.org/details/zhonghua-dadian/%E4%B8%AD%E5%8D%8E%E5%A4%A7%E5%85%B8/%E7%BB%8F%E6%B5%8E%E5%85%B8/%E4%B8%AD%E5%8D%8E%E5%A4%A7%E5%85%B8%20%20%E7%BB%8F%E6%B5%8E%E5%85%B8%20%20%E5%9C%9F%E5%9C%B0%E5%88%B6%E5%BA%A6%E5%88%86%E5%85%B8%20%201_13456908/)

## CBDB cooked data

If you want to use "cooked" CBDB, there are several solutions:

  1. [CBDB API for person name query](https://projects.iq.harvard.edu/cbdb/cbdb-api)
  2. [CBDB API for prosopography research](https://github.com/cbdb-project/cbdb-online-main-server/blob/develop/API.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
  3. [CBDB linked open data](https://projects.iq.harvard.edu/cbdb/cbdb-linked-open-data)
 
Please feel free to let me know if these solutions can help.

Best,
Hongsu
