### ISSUE TITLE
在人物关系页面里，是否能加上他对应的诗文链接

### ISSUE THREAD

**Issue by wdstiger** [cbdb-project/cbdb_sqlite#4]
1、希望能有赠诗、赠文的对应链接
2、希望能有思维导图的方式来展示（3代以内、6度）关系表

**Comment by sudoghut** [comment]
wdstiger 您好，感谢您的建议！这里的 GitHub cbdb-project 是由 CBDB 学术分支维护的社区。我们数据库建设的目标是为了[群体传记学研究](https://projects.iq.harvard.edu/chinesecbdb/%E7%BE%A4%E9%AB%94%E5%82%B3%E8%A8%98%E5%AD%B8)。

## 1. 关于 CBDB 数据和原始文献之间的关联。

我们希望用数据库研究群体性，文化性，地域性，时代性等宏观特征。而更少关注一首诗或者一篇文章。另一方面，因为版权方面的原因，我们会更倾向于对数据挖掘之后的 data points 进行分析，而更少对原文做自然语言分析，或者将数据和原始文本做关联。

## 2. 关于数据可视化。

[CBDB 学术分支](https://projects.iq.harvard.edu/cbdb/home)的目标主要是进行数据挖掘，数据研究，数据分享，以及面向 cyberinfrastructure 的 API 建设。而数据可视化和产品化由 CBDB 商业化分支[引得公司](https://www.inindex.com/)负责。关于数据可视化的建议，您可以直接联络 CBDB 商业化分支：https://www.inindex.com/footerDetail/34

感谢！
